apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
  labels:
    app: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - name: stock
          image: stock
          ports:
            - containerPort: 9002
